<a href="https://colab.research.google.com/github/Ethan-Jeong/test_deeplearning/blob/master/NLP/cos_similarity.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from numpy import dot
from numpy.linalg import norm
import numpy as np
def cos_sim(A, B):
       return dot(A, B)/(norm(A)*norm(B))

In [2]:
doc1=np.array([0,1,1,1])
doc2=np.array([1,0,1,1])
doc3=np.array([2,0,2,2])

In [3]:
print(cos_sim(doc1, doc2)) #문서1과 문서2의 코사인 유사도
print(cos_sim(doc1, doc3)) #문서1과 문서3의 코사인 유사도
print(cos_sim(doc2, doc3)) #문서2과 문서3의 코사인 유사도

0.6666666666666667
0.6666666666666667
1.0000000000000002


In [4]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [5]:
corpus = [
    'you know I want your love',
    'I like you',
    'what should I do ',    
]


In [6]:
tfidf = TfidfVectorizer()
tfidf.fit_transform(corpus).toarray()

array([[0.        , 0.46735098, 0.        , 0.46735098, 0.        ,
        0.46735098, 0.        , 0.35543247, 0.46735098],
       [0.        , 0.        , 0.79596054, 0.        , 0.        ,
        0.        , 0.        , 0.60534851, 0.        ],
       [0.57735027, 0.        , 0.        , 0.        , 0.57735027,
        0.        , 0.57735027, 0.        , 0.        ]])

In [7]:
print(tfidf.vocabulary_)

{'you': 7, 'know': 1, 'want': 5, 'your': 8, 'love': 3, 'like': 2, 'what': 6, 'should': 4, 'do': 0}


## Recommanded with cos simuliaty
dataset from https://www.kaggle.com/rounakbanik/the-movies-dataset/version/7?select=movies_metadata.csv


In [8]:
import pandas as pd

In [12]:
df_data = pd.read_csv('movies_metadata.csv')

/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py:2718: DtypeWarning: Columns (10) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


In [13]:
df_data.head(3)

adult  ... vote_count
0  False  ...     5415.0
1  False  ...     2413.0
2  False  ...       92.0

[3 rows x 24 columns]

In [14]:
df_data.columns

Index(['adult', 'belongs_to_collection', 'budget', 'genres', 'homepage', 'id',
       'imdb_id', 'original_language', 'original_title', 'overview',
       'popularity', 'poster_path', 'production_companies',
       'production_countries', 'release_date', 'revenue', 'runtime',
       'spoken_languages', 'status', 'tagline', 'title', 'video',
       'vote_average', 'vote_count'],
      dtype='object')

In [15]:
df_data['overview']

0        Led by Woody, Andy's toys live happily in his ...
1        When siblings Judy and Peter discover an encha...
2        A family wedding reignites the ancient feud be...
3        Cheated on, mistreated and stepped on, the wom...
4        Just when George Banks has recovered from his ...
                               ...                        
45461          Rising and falling between a man and woman.
45462    An artist struggles to finish his work while a...
45463    When one of her hits goes wrong, a professiona...
45464    In a small town live two brothers, one a minis...
45465    50 years after decriminalisation of homosexual...
Name: overview, Length: 45466, dtype: object

In [16]:
data = df_data.head(10000)

In [17]:
data = data.dropna()

In [18]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 158 entries, 9 to 9888
Data columns (total 24 columns):
 #   Column                 Non-Null Count  Dtype  
---  ------                 --------------  -----  
 0   adult                  158 non-null    object 
 1   belongs_to_collection  158 non-null    object 
 2   budget                 158 non-null    object 
 3   genres                 158 non-null    object 
 4   homepage               158 non-null    object 
 5   id                     158 non-null    object 
 6   imdb_id                158 non-null    object 
 7   original_language      158 non-null    object 
 8   original_title         158 non-null    object 
 9   overview               158 non-null    object 
 10  popularity             158 non-null    object 
 11  poster_path            158 non-null    object 
 12  production_companies   158 non-null    object 
 13  production_countries   158 non-null    object 
 14  release_date           158 non-null    object 
 15  reven

In [19]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [20]:
tfidf = TfidfVectorizer()

In [22]:
tfidf_matrix = tfidf.fit_transform(data['overview'])
tfidf_matrix.shape

(158, 2696)

In [23]:
len(tfidf.vocabulary_)

2696

In [24]:
type(tfidf_matrix)

scipy.sparse.csr.csr_matrix

In [25]:
tfidf_matrix[4].toarray()

array([[0., 0., 0., ..., 0., 0., 0.]])

In [26]:
from sklearn.metrics.pairwise import linear_kernel

In [28]:
cosin_sim = linear_kernel(tfidf_matrix,tfidf_matrix)

In [29]:
type(cosin_sim)

numpy.ndarray

In [30]:
cosin_sim.shape

(158, 158)

In [31]:
cosin_sim[3]

array([0.03403894, 0.07378662, 0.0606532 , 1.        , 0.05231864,
       0.05361942, 0.04305033, 0.01963748, 0.03302958, 0.04013632,
       0.05650286, 0.04380791, 0.045455  , 0.0360105 , 0.07208718,
       0.06037126, 0.02463999, 0.06438099, 0.0261279 , 0.03232211,
       0.03084823, 0.04654037, 0.05100054, 0.02586476, 0.01778496,
       0.05746612, 0.10967293, 0.0282976 , 0.04640804, 0.02406314,
       0.0671682 , 0.03956612, 0.04875229, 0.04437252, 0.02699316,
       0.02809418, 0.04223523, 0.02060186, 0.05070264, 0.03129839,
       0.02382746, 0.03403162, 0.03612028, 0.0502291 , 0.04674237,
       0.07158003, 0.02806686, 0.03066928, 0.07962729, 0.04691775,
       0.00644533, 0.0481169 , 0.03853567, 0.03240614, 0.01586077,
       0.02972285, 0.06138844, 0.02404479, 0.02269754, 0.03191292,
       0.05483523, 0.03238852, 0.10369226, 0.01014625, 0.02365042,
       0.07221074, 0.0937075 , 0.06614349, 0.06212896, 0.03717476,
       0.03104298, 0.04467526, 0.04421634, 0.0348611 , 0.04193

In [36]:
indeces = pd.Series(data.index ,  index=data['title']).drop_duplicates()

In [38]:
indeces['From Dusk Till Dawn']

69

In [39]:
list(cosin_sim[69])

[0.0727441763199051,
 0.02892051203972273,
 0.02996503077446317,
 0.037174758464543475,
 0.02346836061741026,
 0.021246298385504493,
 0.03633447712794377,
 0.02409510202753557,
 0.06229400104850713,
 0.03702937763287602,
 0.02266926258350839,
 0.03550986180781372,
 0.04067791017893172,
 0.02258712427618866,
 0.055681642758578426,
 0.03285809837552814,
 0.008864996791036644,
 0.051654345203359445,
 0.036543295302026296,
 0.05436611020060969,
 0.033444124944652376,
 0.034369941078449484,
 0.015738855191422714,
 0.04867096565015526,
 0.0165640075249569,
 0.045349328897193536,
 0.046479507343680074,
 0.02335116601519331,
 0.03414460067128391,
 0.01880098894929399,
 0.03749684968923591,
 0.03495873912734175,
 0.028904142549040543,
 0.07653702067400137,
 0.0420053856954951,
 0.01887417858509342,
 0.03899075747625005,
 0.018905351270920575,
 0.0581371686844761,
 0.06256835081107805,
 0.06418018781492944,
 0.02818557476486423,
 0.012636801969483472,
 0.03411513362071413,
 0.022011528214427596,

In [45]:
cosin_list = list(enumerate(cosin_sim[69]))
cosin_list

[(0, 0.0727441763199051),
 (1, 0.02892051203972273),
 (2, 0.02996503077446317),
 (3, 0.037174758464543475),
 (4, 0.02346836061741026),
 (5, 0.021246298385504493),
 (6, 0.03633447712794377),
 (7, 0.02409510202753557),
 (8, 0.06229400104850713),
 (9, 0.03702937763287602),
 (10, 0.02266926258350839),
 (11, 0.03550986180781372),
 (12, 0.04067791017893172),
 (13, 0.02258712427618866),
 (14, 0.055681642758578426),
 (15, 0.03285809837552814),
 (16, 0.008864996791036644),
 (17, 0.051654345203359445),
 (18, 0.036543295302026296),
 (19, 0.05436611020060969),
 (20, 0.033444124944652376),
 (21, 0.034369941078449484),
 (22, 0.015738855191422714),
 (23, 0.04867096565015526),
 (24, 0.0165640075249569),
 (25, 0.045349328897193536),
 (26, 0.046479507343680074),
 (27, 0.02335116601519331),
 (28, 0.03414460067128391),
 (29, 0.01880098894929399),
 (30, 0.03749684968923591),
 (31, 0.03495873912734175),
 (32, 0.028904142549040543),
 (33, 0.07653702067400137),
 (34, 0.0420053856954951),
 (35, 0.0188741785850

In [50]:
consin_index = sorted(cosin_list, key=lambda x:x[1] ,reverse=True)

In [52]:
consin_index[1:11]

[(83, 0.15998660887787308),
 (67, 0.14772757089625846),
 (137, 0.13396597843861469),
 (138, 0.12763954217361856),
 (56, 0.12396013932603699),
 (133, 0.1189225068324697),
 (71, 0.11846245157106666),
 (74, 0.11163546861489206),
 (85, 0.10414294242114651),
 (62, 0.1021239662265584)]

In [54]:
# for i in consin_index:
  
movie_indeces = [ i[0] for i in consin_index[1:11] ]

In [56]:
data['title'].iloc[movie_indeces]

3513                      The Spy Who Loved Me
2832                     From Russia with Love
7329                       You Only Live Twice
7330                                 Octopussy
2263                          A View to a Kill
7192    Agent Cody Banks 2: Destination London
2875                          Live and Let Die
2965                   The World Is Not Enough
3517               The Man with the Golden Gun
2572                                    Tarzan
Name: title, dtype: object