<a href="https://colab.research.google.com/github/Ethan-Jeong/test_deeplearning/blob/master/diff_sigmoid_softmax.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# sigmoid

In [2]:
import tensorflow as tf

In [4]:
a = tf.constant([4.0,1.0,3.0], dtype = tf.float32)
a


<tf.Tensor: shape=(3,), dtype=float32, numpy=array([4., 1., 3.], dtype=float32)>

In [7]:
b = tf.keras.activations.sigmoid(a)
b

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([0.98201376, 0.7310586 , 0.95257413], dtype=float32)>

In [8]:
b.numpy()

array([0.98201376, 0.7310586 , 0.95257413], dtype=float32)

# softmax

In [14]:
inputs = tf.random.normal(shape= (1,3))
inputs

<tf.Tensor: shape=(1, 3), dtype=float32, numpy=array([[-2.236372  ,  1.5497358 , -0.24644503]], dtype=float32)>

In [16]:
outputs = tf.keras.activations.softmax(inputs)
outputs

<tf.Tensor: shape=(1, 3), dtype=float32, numpy=array([[0.01908416, 0.84131527, 0.13960062]], dtype=float32)>

In [13]:
outputs.numpy() # 세 값의 합이 1을 넘지 않음 => 

array([[0.4020441 , 0.47335675, 0.12459911]], dtype=float32)