<a href="https://colab.research.google.com/github/Ethan-Jeong/test_deeplearning/blob/master/Multi_perceptron.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf

In [2]:
x_data = [[0,0],
          [1,0],
          [0,1],
          [1,1]]
y_data = [[0],
          [1],
          [1],
          [1]] 
type(x_data), type(y_data), 

(list, list)

In [3]:
import numpy as np
x_train = np.array(x_data)
y_train = np.array(y_data)
x_train.shape, y_train.shape

((4, 2), (4, 1))

## create model

In [4]:
model = tf.keras.models.Sequential()

# solve XOR model
model.add(tf.keras.Input(shape=(2,))) # input layer
model.add(tf.keras.layers.Dense(2, activation='sigmoid')) # 기능 layer
# model.add(tf.keras.layers.Dense(128, activation='sigmoid')) # 기능 layer
model.add(tf.keras.layers.Dense(1, activation='sigmoid')) # output layer

model.compile(optimizer='sgd', loss='mse', metrics=['acc'])

In [5]:
# tf.keras.utils.plot_model(model, show_shapes=True)

In [6]:
model.fit(x_train, y_train, epochs=100)

Epoch 1/100
1/1 [==============================] - 1s 673ms/step - loss: 0.2529 - acc: 0.7500
Epoch 2/100
1/1 [==============================] - 0s 14ms/step - loss: 0.2527 - acc: 0.7500
Epoch 3/100
1/1 [==============================] - 0s 9ms/step - loss: 0.2526 - acc: 0.7500
Epoch 4/100
1/1 [==============================] - 0s 6ms/step - loss: 0.2524 - acc: 0.7500
Epoch 5/100
1/1 [==============================] - 0s 5ms/step - loss: 0.2523 - acc: 0.7500
Epoch 6/100
1/1 [==============================] - 0s 3ms/step - loss: 0.2522 - acc: 0.7500
Epoch 7/100
1/1 [==============================] - 0s 5ms/step - loss: 0.2520 - acc: 0.7500
Epoch 8/100
1/1 [==============================] - 0s 4ms/step - loss: 0.2519 - acc: 0.7500
Epoch 9/100
1/1 [==============================] - 0s 6ms/step - loss: 0.2517 - acc: 0.7500
Epoch 10/100
1/1 [==============================] - 0s 6ms/step - loss: 0.2516 - acc: 0.7500
Epoch 11/100
1/1 [==============================] - 0s 5ms/step - loss: 0.25

In [7]:
# model.predict([[0,1]])   # dense : 2, epochs : 100, loss : 0.20  --> 0.53

In [8]:
# model.predict([[0,1]])    # dense : 128,  epochs : 100, loss: 0.2101 --> 0.72344226

In [9]:
model.predict([[0,1]])    # dense : 128*2, loss: 0.1864 --> 0.73873436

array([[0.61339706]], dtype=float32)

In [10]:
model.evaluate(x_train, y_train)

1/1 [==============================] - 0s 125ms/step - loss: 0.2403 - acc: 0.7500


[0.24025005102157593, 0.75]

In [11]:
model.weights

[<tf.Variable 'dense/kernel:0' shape=(2, 2) dtype=float32, numpy=
 array([[-0.87721294,  1.1209537 ],
        [-0.769751  , -0.19336939]], dtype=float32)>,
 <tf.Variable 'dense/bias:0' shape=(2,) dtype=float32, numpy=array([ 0.01403469, -0.00242771], dtype=float32)>,
 <tf.Variable 'dense_1/kernel:0' shape=(2, 1) dtype=float32, numpy=
 array([[ 1.3711911 ],
        [-0.13252716]], dtype=float32)>,
 <tf.Variable 'dense_1/bias:0' shape=(1,) dtype=float32, numpy=array([0.08321027], dtype=float32)>]

In [12]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 2)                 6         
_________________________________________________________________
dense_1 (Dense)              (None, 1)                 3         
Total params: 9
Trainable params: 9
Non-trainable params: 0
_________________________________________________________________
