<a href="https://colab.research.google.com/github/Ethan-Jeong/test_deeplearning/blob/master/NaverSentimentAnalysis_loadmodel_LSTM.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import tensorflow as tf

In [4]:
loaded_model = tf.keras.models.load_model('./NaverSentimentAnalysis_LSTM.h5')
loaded_model

In [5]:
!python -m pip install konlpy

     |████████████████████████████████| 19.4 MB 123 kB/s 
     |████████████████████████████████| 86 kB 5.6 MB/s 
     |████████████████████████████████| 448 kB 51.9 MB/s 
  Attempting uninstall: beautifulsoup4
    Found existing installation: beautifulsoup4 4.6.3
    Uninstalling beautifulsoup4-4.6.3:
      Successfully uninstalled beautifulsoup4-4.6.3


In [6]:
import konlpy

In [7]:
import pickle

In [8]:
stopwords = pickle.load(open('./stopwords.pkl','rb'))

In [9]:
okt = konlpy.tag.Okt()
new_sentence = okt.morphs('감독이 예술이네.',stem=True)
new_sentence = [  tok for tok in new_sentence if tok not in stopwords ] 
new_sentence

['감독', '예술', '이네', '.']

In [10]:
tokenizer = pickle.load(open('./tokenizer.pkl','rb'))
tokenizer

In [12]:
encoded = tokenizer.texts_to_sequences([new_sentence])
# encoded
pad_new = tf.keras.preprocessing.sequence.pad_sequences(encoded,maxlen=50)
pad_new

array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,  92, 128,   1]],
      dtype=int32)

In [13]:
vob_size = len(tokenizer.word_index)
vob_size

1572

In [16]:
# 감독이 예술이네. --> 웹 사용자 입력.
score = loaded_model.predict(pad_new)
score

array([[0.507535]], dtype=float32)

In [17]:
if(score > 0.5 ):
  print('긍정.',score)
else:
  print('부정.',score)

긍정. [[0.507535]]


In [20]:
def sentiment_predict(sentence):
  okt = konlpy.tag.Okt()
  new_sentence = okt.morphs(sentence,stem=True)
  new_sentence = [  tok for tok in new_sentence if tok not in stopwords ] 
  encoded = tokenizer.texts_to_sequences([new_sentence])
  pad_new = tf.keras.preprocessing.sequence.pad_sequences(encoded,maxlen=50)
  score = loaded_model.predict(pad_new)
  return score

In [21]:
words = '이 영화 꽝이네.'
sentiment_predict(words)

array([[0.5079713]], dtype=float32)