<a href="https://colab.research.google.com/github/Ethan-Jeong/test_deeplearning/blob/master/Notescale_LSTM.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
note_seq = ['g8', 'e8', 'e4', 'f8', 'd8', 'd4', 'c8', 'd8', 'e8', 'f8', 'g8', 'g8', 'g4',
       'g8', 'e8', 'e8', 'e8', 'f8', 'd8', 'd4', 'c8', 'e8', 'g8', 'g8', 'e8', 'e8', 'e4',
       'd8', 'd8', 'd8', 'd8', 'd8', 'e8', 'f4', 'e8', 'e8', 'e8', 'e8', 'e8', 'f8', 'g4',
       'g8', 'e8', 'e4', 'f8', 'd8', 'd4', 'c8', 'e8', 'g8', 'g8', 'e8', 'e8', 'e4']


In [2]:
code2idx = {'c4':0, 'd4':1, 'e4':2, 'f4':3, 'g4':4, 'a4':5, 'b4':6,
            'c8':7, 'd8':8, 'e8':9, 'f8':10, 'g8':11, 'a8':12, 'b8':13}


In [3]:
note_seq[0:4] , note_seq[1:5] , note_seq[2:6]

(['g8', 'e8', 'e4', 'f8'], ['e8', 'e4', 'f8', 'd8'], ['e4', 'f8', 'd8', 'd4'])

In [4]:
dataset = list()

for i in range(len(note_seq)-4):
  subnet = note_seq[i:i+4]
  items = list()
  # print(subnet)
  for item in subnet:
    # print(code2idx[item])
    items.append(code2idx[item])
  # print(items)
  dataset.append(items)
print(dataset)

[[11, 9, 2, 10], [9, 2, 10, 8], [2, 10, 8, 1], [10, 8, 1, 7], [8, 1, 7, 8], [1, 7, 8, 9], [7, 8, 9, 10], [8, 9, 10, 11], [9, 10, 11, 11], [10, 11, 11, 4], [11, 11, 4, 11], [11, 4, 11, 9], [4, 11, 9, 9], [11, 9, 9, 9], [9, 9, 9, 10], [9, 9, 10, 8], [9, 10, 8, 1], [10, 8, 1, 7], [8, 1, 7, 9], [1, 7, 9, 11], [7, 9, 11, 11], [9, 11, 11, 9], [11, 11, 9, 9], [11, 9, 9, 2], [9, 9, 2, 8], [9, 2, 8, 8], [2, 8, 8, 8], [8, 8, 8, 8], [8, 8, 8, 8], [8, 8, 8, 9], [8, 8, 9, 3], [8, 9, 3, 9], [9, 3, 9, 9], [3, 9, 9, 9], [9, 9, 9, 9], [9, 9, 9, 9], [9, 9, 9, 10], [9, 9, 10, 4], [9, 10, 4, 11], [10, 4, 11, 9], [4, 11, 9, 2], [11, 9, 2, 10], [9, 2, 10, 8], [2, 10, 8, 1], [10, 8, 1, 7], [8, 1, 7, 9], [1, 7, 9, 11], [7, 9, 11, 11], [9, 11, 11, 9], [11, 11, 9, 9]]


In [5]:
import numpy as np

In [6]:
datasets = np.array(dataset)

In [7]:
x_train = datasets[:,0:3]
x_train.shape

(50, 3)

In [8]:
y_train = datasets[:,3]
y_train.shape

(50,)

In [9]:
len(code2idx)

14

In [10]:
x_train = x_train / 13 # len(code2idx)
x_train[3]

array([0.76923077, 0.61538462, 0.07692308])

# make model

In [11]:
import tensorflow as tf

In [12]:
x_train.shape , x_train[2] # --> tensorflow type(tensor) ( 50 , 3 ,1 )

((50, 3), array([0.15384615, 0.76923077, 0.61538462]))

In [13]:
X_train = np.reshape(x_train,(50,3,1))
X_train.shape , X_train[2]

((50, 3, 1), array([[0.15384615],
        [0.76923077],
        [0.61538462]]))

In [14]:
np.unique(y_train) , len(np.unique(y_train))

(array([ 1,  2,  3,  4,  7,  8,  9, 10, 11]), 9)

In [19]:
model = tf.keras.models.Sequential()

 # ( batch_sieze , timesteps , input_dim ) -> ( rows , cols , 1 )
model.add(tf.keras.Input(shape=(3,1)))
model.add( tf.keras.layers.LSTM(128)) # input layer and hidden layer
model.add( tf.keras.layers.Dense( 13 , activation='softmax' )) # ouput layer


model.compile(optimizer='adam',loss='sparse_categorical_crossentropy',metrics='accuracy' ) # gadget

In [ ]:
hist = model.fit(X_train,y_train,epochs=500,batch_size=10) # 속도를 빠르게 하기 위해서 batch_size 를 올려주면 된다.

In [31]:
model.evaluate(X_train,y_train)

2/2 [==============================] - 0s 8ms/step - loss: 1.2122 - accuracy: 0.4800


[1.2121559381484985, 0.47999998927116394]

In [26]:
X_train[0:1]

array([[[0.84615385],
        [0.69230769],
        [0.15384615]]])

In [33]:
model.predict(X_train[0:1])

array([[1.3730554e-06, 2.3510505e-03, 3.8305499e-02, 2.9100926e-04,
        1.3261532e-03, 1.3425284e-06, 9.7670375e-07, 2.7535824e-02,
        2.2069449e-02, 8.1911862e-02, 8.1404173e-01, 1.2163369e-02,
        3.7035161e-07]], dtype=float32)

In [34]:
pred = model.predict(X_train[0:1])

In [35]:
np.argmax(pred)

10

In [ ]:
code2idx = {'c4':0, 'd4':1, 'e4':2, 'f4':3, 'g4':4, 'a4':5, 'b4':6,
            'c8':7, 'd8':8, 'e8':9, 'f8':10, 'g8':11, 'a8':12, 'b8':13}

In [ ]:
note_seq = ['g8', 'e8', 'e4', 'f8', 'd8', 'd4', 'c8', 'd8', 'e8', 'f8', 'g8', 'g8', 'g4',
       'g8', 'e8', 'e8', 'e8', 'f8', 'd8', 'd4', 'c8', 'e8', 'g8', 'g8', 'e8', 'e8', 'e4',
       'd8', 'd8', 'd8', 'd8', 'd8', 'e8', 'f4', 'e8', 'e8', 'e8', 'e8', 'e8', 'f8', 'g4',
       'g8', 'e8', 'e4', 'f8', 'd8', 'd4', 'c8', 'e8', 'g8', 'g8', 'e8', 'e8', 'e4']