<a href="https://colab.research.google.com/github/Ethan-Jeong/test_deeplearning/blob/master/tensorflow_guideWithIris.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from sklearn import datasets

In [2]:
iris = datasets.load_iris()

In [3]:
import pandas as pd

In [6]:
df_iris = pd.DataFrame(iris.data)
df_iris.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   0       150 non-null    float64
 1   1       150 non-null    float64
 2   2       150 non-null    float64
 3   3       150 non-null    float64
dtypes: float64(4)
memory usage: 4.8 KB


In [7]:
import sqlite3
connect = sqlite3.connect('./db.sqlite3')
df_iris.to_sql('iris_resource',connect,if_exists='append',index=False)

In [8]:
df_load = pd.read_sql_query('select * from iris_resource ' , connect )
df_load.head(4)

0    1    2    3
0  5.1  3.5  1.4  0.2
1  4.9  3.0  1.4  0.2
2  4.7  3.2  1.3  0.2
3  4.6  3.1  1.5  0.2

In [9]:
x_data = df_load.to_numpy()
x_data.shape

(150, 4)

In [15]:
import numpy as np

In [17]:
y_data = iris.target
y_data , np.unique(y_data)

(array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2]),
 array([0, 1, 2]))

# 교육단계

In [11]:
import tensorflow as tf

In [12]:
model = tf.keras.Sequential()

In [20]:

model.add(tf.keras.Input(shape=(4,))) # input layer
model.add(tf.keras.layers.Dense(64,activation='relu')) # hidden layer / default relu
model.add(tf.keras.layers.Dense(24,activation='relu')) # hidden layer / default relu
model.add(tf.keras.layers.Dense(3,activation='softmax')) # ouput layer / 보기가 두가지 이면 sigmoid , 세가지 이상이면 softmax


model.compile(optimizer='adam', loss='mse' , metrics=['acc']) 
# gadget / default -> optimizer='adam', loss='mse' / optimizer 로 기울기를 구하고 loss 를 확인하여 다음 값을 올릴지 내릴지 판단

In [21]:
model.fit(x_data , y_data , epochs=50 , validation_split=0.3 ) # 학습  ephochs : 반복횟수

Epoch 1/50
4/4 [==============================] - 1s 65ms/step - loss: 0.3973 - acc: 0.4762 - val_loss: 2.7779 - val_acc: 0.0000e+00
Epoch 2/50
4/4 [==============================] - 0s 10ms/step - loss: 0.3969 - acc: 0.2476 - val_loss: 2.7778 - val_acc: 0.8667
Epoch 3/50
4/4 [==============================] - 0s 10ms/step - loss: 0.3969 - acc: 0.4667 - val_loss: 2.7778 - val_acc: 0.0000e+00
Epoch 4/50
4/4 [==============================] - 0s 9ms/step - loss: 0.3969 - acc: 0.4762 - val_loss: 2.7778 - val_acc: 0.0000e+00
Epoch 5/50
4/4 [==============================] - 0s 9ms/step - loss: 0.3968 - acc: 0.4762 - val_loss: 2.7778 - val_acc: 0.5111
Epoch 6/50
4/4 [==============================] - 0s 10ms/step - loss: 0.3968 - acc: 0.0762 - val_loss: 2.7778 - val_acc: 0.1333
Epoch 7/50
4/4 [==============================] - 0s 10ms/step - loss: 0.3968 - acc: 0.2381 - val_loss: 2.7778 - val_acc: 0.0000e+00
Epoch 8/50
4/4 [==============================] - 0s 10ms/step - loss: 0.3968 - acc

#Evaluation : 평가

In [22]:
model.evaluate(x_data,y_data)

5/5 [==============================] - 0s 3ms/step - loss: 1.1111 - acc: 0.1000


[1.111111044883728, 0.10000000149011612]

# 서비스 단계

In [23]:
x_data[25] ,y_data[25]

(array([5. , 3. , 1.6, 0.2]), 0)

In [25]:
pred = model.predict([[5. , 3. , 1.6, 0.2]])
pred

array([[0.33327878, 0.33323   , 0.33349124]], dtype=float32)

In [28]:
import numpy as np
np.argmax(pred)

2